### PR TITLE
Added a feature that enables speedtests to be configured not to run on every tick

### PR DESCRIPTION
**Pull request by motorolja**
While using the application I noticed if I wanted to have decent accuracy while running speed test my data usage got huge. Just setting the interval to very slow is not an option since I also want to keep track of the signal strength. 

The download and upload speed does not change as much as the signal strength. So to enable high accuracy on the speed test I just made it so that the test is not run on every tick, there are different levels of how often one want to run the speed test.

The implementation for the network change and dbm change options are probably not the most accurate since I only check these when the application requests a speed test and not when the changes occurs.

### CODE REVIEW

**Comment by caarmen** [comment]
Many thanks for your submission. I currently am not at my pc: I've only
looked at the pull request on my phone. I hope to be able to look at it
more in detail soon.

I have a couple of comments though:

In the upload and download data sources, you added some static fields. Why
are they static?

In the same files, in the switch case over the different intervals, there's
a lot of copy /paste. I think this can be reduced simply by having one
single implementation for all those cases which are copied /pasted.

In one file, I believe I saw an alert dialog added with the title and
message hard-coded in Java. These strings should go into a string xml file.
But I'm not even sure there should be a warning dialog there...

Thanks again! I hope to be able to look at this further, soon.

**Comment by motorolja** [comment]
The static values in upload and download data are just there to reduce the cost of recreating them, though I assume there are currently only 1 instance of each data source always now which means that it does not matter whether or not they are static. I usually always want to do static on member classes when possible since they are generally more expensive to recreate.

Yes a lot of copy paste, should be put in a separate class. I am working on factoring them out.

The alert message is removed, wasent saying anything useful.

**Comment by caarmen** [comment]
Thanks for the refactoring! 

Can you define some constants for -1 and -2 instead of using int literals? 

In the switch case, you can use these constants for the first two cases, and then merge all the remaining cases into a single default case, since they all have exactly the same logic.

Thanks :-)

**Comment by caarmen** [comment]
Also it looks like mDifference could be a static final constant instead of a member field. And maybe with a slightly more descriptive name? Like SIGNAL_STRENGTH_VARIATION_THRESHOLD_DBM. Yeah, it's a bit verbose, but you know exactly what it is :-)

**Comment by caarmen** [comment]
Thanks for your last changes.

For info, I've created a branch in my repo, motorolja_speed_test_interval.

I've merged your master branch into that branch, I've done some changes, and I'm just working on testing right now.

Summary of changes:
* Moved some classes around into different packages
* Renamed the SpeedTestAdvancedInterval class to SpeedTestExecutionDecider and renamed some of its methods
* Removed the "advanced" setting. Instead, I added another value to the interval preference: "every log entry".  This is the default value for that setting, and is equivalent to the behavior before any of these changes.
* When looking at the signal strength, check the wifi signal strength if we're on wifi, and the cell signal strength if we're on mobile data.
* Change the way we retrieve the wifi signal strength, cell signal strength, and networktype of the last speed test: I now read this from the database.  Reading from the DB adds a slight perf hit since it involves disk read, but this should be negligible, given that the tests can only be done at most once every 10 seconds. I think the code is a bit easier to follow this way, rather than keeping track of "last" and "old" fields in memory for all these fields.
* Only listen to phone state changes if the "5 dBm" setting is selected.
* Call the onDestroy() method (it wasn't called since the commit to move the logic into SpeedTestAdvancedInterval)
* Some fixes for some minor issues highlighted by Android Studio code inspection (unused imports, visibility, reformatting files...)
* Translated the new strings into French and Spanish. 
* Added your name to the copyright headers of the files you contributed to :)

You can see the changes here:
https://github.com/caarmen/network-monitor/compare/motorolja_speed_test_interval?expand=1

Once I've done enough testing, I'll merge this into the master :)

Thanks again!

**Comment by caarmen** [comment]
Merged into master.

**Pull request closed without merging**
